version: 0.0
os: windows
files:
  - source: \index.html
    destination: c:\inetpub\wwwroot\webtest
  - source: \css\site.css
    destination: c:\inetpub\wwwroot\webtest\css
  - source: \deletewebsite.ps1
    destination: c:\temp
  - source: \installwebsite.ps1
    destination: c:\temp
  - source: \deletewebsite.bat
    destination: c:\temp
  - source: \installwebsite.bat
    destination: c:\temp
hooks:
  BeforeInstall:
    - location: \deletewebsite.bat
      timeout: 180
  AfterInstall:
    - location: \installwebsite.bat
      timeout: 180